# dein本体

  [[plugins]]
  repo = 'Shougo/dein.vim'


# ---------------------------------
# vaffle
#     ファイルツリー
# ---------------------------------
  [[plugins]]
  repo = 'cocopon/vaffle.vim'
  hook_add = '''
    source ~/.config/nvim/plugins/vaffle.vim
  '''

# ---------------------------------
# vim-fugitive
# vim-gitgutter
#     Git 支援プラグイン
# ---------------------------------
  [[plugins]]
  repo = 'tpope/vim-fugitive'
  hook_add = '''
    source ~/.config/nvim/plugins/fugitive.vim
  '''
  [[plugins]]
  repo = 'airblade/vim-gitgutter'
  hook_add = '''
    source ~/.config/nvim/plugins/vim-gitgutter.vim
  '''

# ---------------------------------
# vim-zenspace
#     全角スペースのハイライト
# ---------------------------------
  [[plugins]]
  repo = 'thinca/vim-zenspace'

# ---------------------------------
# vimdoc-ja
# 日本語のドキュメント
# ---------------------------------
  [[plugins]]
  repo = 'vim-jp/vimdoc-ja.git'


# ---------------------------------
# Color Schemes
#     カラースキーマ
# ---------------------------------
  [[plugins]]
  repo = 'NLKNguyen/papercolor-theme'
