# ---------------------------------
# deoplete-tabnine
#     補完
# ---------------------------------
  [[plugins]]
  repo = 'tbodt/deoplete-tabnine'
  build = './install.sh'


# ---------------------------------
# toml
# ---------------------------------
  [[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = ['toml']
